# - global information demand matrix
# - global information


OUTPUT_FLAG = False
BUSY_PARAMETER = 4

STATIONCAPACITY_PARAMETER = 10
TOTALBIKES_PARAMETER = 0.7

VEHICLECAPACITY_PARAMETER = 20
SEED_PARAMETER = 10102019

NITERATIONS_PARAMETER = 50

EPISODELENGTH_PARAMETER = 2  # in days
