# - global information demand matrix
# - global information


OUTPUT_FLAG = False
BUSY_PARAMETER = 4

STATIONCAPACITY_PARAMETER = 10
TOTALBIKES_PARAMETER = 0.7

VEHICLECAPACITY_PARAMETER = 20
SEED_PARAMETER = 10102019

NITERATIONS_PARAMETER = 50

EPISODELENGTH_PARAMETER = 0.1  # in days

STEPS_BETWEEN_UPDATE = 200

REPLAY_BUFFER_SIZE = 5000


MIN_REPLAY_BUFFER_SIZE = 2500

BATCH_SIZE = 2048

DISCOUNT = 0.98

EPSILON_DECAY = 0.995
MIN_EPSILON = 0.001
